services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${WEB_PORT}:80/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ""
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq:/etc/dnsmasq.d'
    restart: unless-stopped

volumes:
  pihole:
  dnsmasq: