services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:9090"
    volumes:
      - linkding-data:/etc/linkding/data
    restart: unless-stopped

volumes:
  linkding-data:
